steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/cookmate"
      - "."

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/cookmate"

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "cookmate"
      - "--image"
      - "gcr.io/$PROJECT_ID/cookmate"
      - "--allow-unauthenticated"
      - "--region"
      - "asia-southeast1"
      - "--min-instances=1"
      - "--max-instances=50"
      - "--port=8050"
      - "--cpu=2"
      - "--memory=4Gi"
images:
  - "gcr.io/$PROJECT_ID/cookmate"
